import type { OrderStatus } from '@/constants/orderStatus';

export type AdminOrder = {
  id: string;
  orderId?: string;
  customerId: string;
  restaurantId: string;
  deliveryPartnerId: string | null;
  totalBagAmount: string;
  deliveryFee: string;
  platformCommission: string;
  totalPaymentAmount: string;
  total_amount?: string;
  discountAmount: string;
  couponCode: string | null;
  walletAmountUsed: string;
  finalAmountPaid: string | null;
  deliveryAddressSnapshot: string;
  deliveryLatitude: string;
  deliveryLongitude: string;
  customerNameSnapshot: string | null;
  customerPhoneSnapshot: string;
  customerEmailSnapshot: string | null;
  notesToRestaurant: string | null;
  orderStatus: OrderStatus;
  paymentStatus: 'paid' | 'pending' | 'failed';
  paymentTransactionId: string | null;
  paymentMethod: string | null;
  orderDate: string;
  restaurantConfirmedAt: string | null;
  deliveryPartnerAssignedAt: string | null;
  pickupTimeSlotStart: string | null;
  pickupTimeSlotEnd: string | null;
  expectedDeliveryTime: string | null;
  actualDeliveryTime: string | null;
  cancellationReason: string | null;
  cancelledByUserType: string | null;
  createdAt: string;
  updatedAt: string;
  customerName: string | null;
  customerPhone: string | null;
  restaurantName: string | null;
  restaurantContactPerson: string | null;
  deliveryPartnerName: string | null;
  deliveryPartnerPhone: string | null;
  items: Array<{
    bagId: string;
    bagName: string;
    bagIsVegetarian: boolean;
    quantity: number;
    pricePaid: number;
    actualWorth: number;
    co2SavedKg: number;
  }>;
};

export type GroceryOrder = {
  id: string;
  customerId: string;
  storeId: string;
  deliveryPartnerId: string | null;
  storeNameSnapshot: string;
  storeImage: string | null;
  totalItemsAmount: string;
  deliveryCharge: string;
  handlingCharge: string;
  platformCommission: string;
  gstAmount: string;
  discountAmount: string;
  totalPaymentAmount: string;
  deliveryAddressSnapshot: string | null;
  orderStatus: string;
  order_status?: string;
  paymentMethod: string | null;
  paymentStatus: string;
  customerNameSnapshot: string | null;
  customerName: string | null;
  customerPhone: string | null;
  createdAt: string;
  updatedAt: string;
  items: Array<{
    id: string;
    groceryItemId: string;
    itemName: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
  }>;
};
